export const BUTTON_CLICK = 'AUTOMATION_LETTER/BUTTON_CLICK';
export const LEVEL_REPEAT = 'AUTOMATION_LETTER/LEVEL_REPEAT_NULL_BUTTON_CLICK';
export const TAKE_PRIZE_NULL_ALL_BUTTON_CLICK = 'AUTOMATION_LETTER/TAKE_PRIZE_NULL_ALL_BUTTON_CLICKK';


export const BUTTON_BLOCK_COMPLETED = 'AUTOMATION_LETTER_BLOCKS_COMPLETED/BUTTON_BLOCK_COMPLETED';
export const BUTTON_BLOCK_REPEAT = 'AUTOMATION_LETTER_BLOCKS_COMPLETED/NULL_LEVEL_BUTTON_BLOCK_REPEAT';
export const TAKE_PRIZE_NULL_ALL_FLAGS_LETTER = 'AUTOMATION_LETTER_BLOCKS_COMPLETED/TAKE_PRIZE_NULL_ALL_FLAGS_LETTER';


export const FLAG_FINAL_LETTER = 'AUTOMATION_FLAGS_LETTER_FINAL/FLAG_FINAL_LETTER';
export const TAKE_PRIZE_FLAG_NULL = 'AUTOMATION_FLAGS_LETTER_FINAL_NULL/TAKE_PRIZE_FLAG_NULL';

export const BUTTON_LEVEL_COMPLETED = 'AUTOMATION_LETTER_FLAGS_LEVEL/BUTTON_LEVEL_COMPLETED';
export const BUTTON_LEVEL_REPEAT = 'AUTOMATION_LETTER_FLAGS_LEVEL/BUTTON_LEVEL_REPEAT';
export const TAKE_PRIZE_ALL_LEVELS_NULL = 'AUTOMATION_LETTER_FLAGS_LEVEL/TAKE_PRIZE_ALL_LEVELS_NULL';

export const BUTTON_BLOCK_LOCAL_STORAGE = 'AUTOMATION_FLAGS_LEVEL_COMPLETED/BUTTON_BLOCK_LOCAL_STORAGE';

export const LEVEL_WORD_COMPLETED = 'AUTOMATION_FLAGS_LEVEL_COMPLETED/LEVEL_WORD_COMPLETED';

export const LEVEL_WORD_REPEAT = 'AUTOMATION_FLAGS_LEVEL_COMPLETED/LEVEL_WORD_REPEAT';

export const FLAG_FINAL_LETTER_WORDS = 'AUTOMATION_FLAGS_LEVEL_COMPLETED/FLAG_FINAL_LETTER_WORDS';



