export const BUTTON_CLICK = 'AUTOMATION_FLAGS_LEVEL_COMPLETED/BUTTON_CLICK';
export const BUTTON_BLOCK_COMPLETED = 'AUTOMATION_FLAGS_LEVEL_COMPLETED/BUTTON_BLOCK_COMPLETED';
export const FLAG_FINAL_LETTER = 'AUTOMATION_FLAGS_LEVEL_COMPLETED/FLAG_FINAL_LETTER';

export const BUTTON_LEVEL_COMPLETED = 'AUTOMATION_FLAGS_LEVEL_COMPLETED/BUTTON_LEVEL_COMPLETED';