export const LETTER_LEVEL_END = 'AUTOMATION_LETTER/LETTER_LEVEL_END';
export const REMOVE_PRIZE = 'PRIZE_SHOP_SELECT_IMG/REMOVE_PRIZE';
export const BOX_COINS_DEPOSIT = 'COINS_LEVEL/BOX_COINS_DEPOSIT';