export const LETTER_LEVEL_END = 'PROGRESS_LETTERS_PRIZES/LETTER_LEVEL_END';
export const LOAD_FROM_LOCAL_STORAGE_LETTER_PRIZES = 'PROGRESS_LETTERS_PRIZES/LOAD_FROM_LOCAL_STORAGE_LETTER_PRIZES';
export const PUSH_PRIZE_LETTER = 'PROGRESS_LETTERS_PRIZES/PUSH_PRIZE_LETTER';

export const REMOVE_PRIZE = 'PRIZE_SHOP_SELECT_IMG/REMOVE_PRIZE';
export const LOAD_LOCAL_STORAGE_FLAG_SHOP_PRIZE = 'PRIZE_SHOP_SELECT_IMG/LOAD_LOCAL_STORAGE_FLAG_SHOP_PRIZE';

export const BOX_COINS_DEPOSIT = 'BOX_COINS_LEVEL/BOX_COINS_DEPOSIT';
export const LOAD_FROM_LOCAL_STORAGE_BOX_COINS = 'BOX_COINS_LEVEL/LOAD_FROM_LOCAL_STORAGE_BOX_COINS';

export const FLAG_GET_PRIZE = 'PRIZE_SHOP_FLAG_GET_PRIZE/FLAG_GET_PRIZE';
export const LOAD_FROM_LOCAL_STORAGE_GET_PRIZE = 'PRIZE_SHOP_FLAG_GET_PRIZE/LOAD_FROM_LOCAL_STORAGE_GET_PRIZE';

export const SELECT_IMG_PRIZE = 'PRIZE_SHOP/SELECT_IMG_PRIZE';