export const LETTERS_SELECT = 'AUTOMATION_TYPES_LETTERS/LETTERS_SELECT';
export const CHANGE_LETTERS_BLOCKS = 'AUTOMATION_TYPES_LETTERS/CHANGE_LETTERS_BLOCKS';
export const SOURCE_STATE_LETTERS_BLOCKS = 'AUTOMATION_TYPES_LETTERS/SOURCE_STATE_LETTERS_BLOCKS';
